type t;
let create : code::int => options::array (int,string) => token::string => t;
let ident : t => (string, int);
let code : t => int;
let code_as_string : t => string;
let uri_path : t => string;
let uri_host : t => string;
let content_format : t => int;
let content_format_as_string : t => string;
let token : t => string;
let observed : array (int, string) => string;
let max_age : array (int, string) => Int32.t;
let log_entry : t => string;